// +build !ignore_autogenerated

/*
Copyright 2018 Alauda.io.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package devops

import (
	time "time"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingCondition) DeepCopyInto(out *BindingCondition) {
	*out = *in
	if in.LastAttempt != nil {
		in, out := &in.LastAttempt, &out.LastAttempt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingCondition.
func (in *BindingCondition) DeepCopy() *BindingCondition {
	if in == nil {
		return nil
	}
	out := new(BindingCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPipelineTaskTemplate) DeepCopyInto(out *ClusterPipelineTaskTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPipelineTaskTemplate.
func (in *ClusterPipelineTaskTemplate) DeepCopy() *ClusterPipelineTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterPipelineTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPipelineTaskTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPipelineTaskTemplateList) DeepCopyInto(out *ClusterPipelineTaskTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPipelineTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPipelineTaskTemplateList.
func (in *ClusterPipelineTaskTemplateList) DeepCopy() *ClusterPipelineTaskTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterPipelineTaskTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPipelineTaskTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPipelineTemplate) DeepCopyInto(out *ClusterPipelineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPipelineTemplate.
func (in *ClusterPipelineTemplate) DeepCopy() *ClusterPipelineTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterPipelineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPipelineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPipelineTemplateList) DeepCopyInto(out *ClusterPipelineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPipelineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPipelineTemplateList.
func (in *ClusterPipelineTemplateList) DeepCopy() *ClusterPipelineTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterPipelineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPipelineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeRepositoryRef) DeepCopyInto(out *CodeRepositoryRef) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeRepositoryRef.
func (in *CodeRepositoryRef) DeepCopy() *CodeRepositoryRef {
	if in == nil {
		return nil
	}
	out := new(CodeRepositoryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.LastAttempt != nil {
		in, out := &in.LastAttempt, &out.LastAttempt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstValues) DeepCopyInto(out *ConstValues) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make(map[string]TaskConstValue, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstValues.
func (in *ConstValues) DeepCopy() *ConstValues {
	if in == nil {
		return nil
	}
	out := new(ConstValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisplayName) DeepCopyInto(out *DisplayName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisplayName.
func (in *DisplayName) DeepCopy() *DisplayName {
	if in == nil {
		return nil
	}
	out := new(DisplayName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportShowOptions) DeepCopyInto(out *ExportShowOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportShowOptions.
func (in *ExportShowOptions) DeepCopy() *ExportShowOptions {
	if in == nil {
		return nil
	}
	out := new(ExportShowOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExportShowOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalParameter) DeepCopyInto(out *GlobalParameter) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(I18nName)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalParameter.
func (in *GlobalParameter) DeepCopy() *GlobalParameter {
	if in == nil {
		return nil
	}
	out := new(GlobalParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPort) DeepCopyInto(out *HostPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPort.
func (in *HostPort) DeepCopy() *HostPort {
	if in == nil {
		return nil
	}
	out := new(HostPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPortStatus) DeepCopyInto(out *HostPortStatus) {
	*out = *in
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(time.Duration)
		**out = **in
	}
	if in.LastAttempt != nil {
		in, out := &in.LastAttempt, &out.LastAttempt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPortStatus.
func (in *HostPortStatus) DeepCopy() *HostPortStatus {
	if in == nil {
		return nil
	}
	out := new(HostPortStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *I18nName) DeepCopyInto(out *I18nName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new I18nName.
func (in *I18nName) DeepCopy() *I18nName {
	if in == nil {
		return nil
	}
	out := new(I18nName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JenkinsAgent) DeepCopyInto(out *JenkinsAgent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JenkinsAgent.
func (in *JenkinsAgent) DeepCopy() *JenkinsAgent {
	if in == nil {
		return nil
	}
	out := new(JenkinsAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JenkinsPlugin) DeepCopyInto(out *JenkinsPlugin) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JenkinsPlugin.
func (in *JenkinsPlugin) DeepCopy() *JenkinsPlugin {
	if in == nil {
		return nil
	}
	out := new(JenkinsPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JenkinsfilePreview) DeepCopyInto(out *JenkinsfilePreview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JenkinsfilePreview.
func (in *JenkinsfilePreview) DeepCopy() *JenkinsfilePreview {
	if in == nil {
		return nil
	}
	out := new(JenkinsfilePreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JenkinsfilePreview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JenkinsfilePreviewOptions) DeepCopyInto(out *JenkinsfilePreviewOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.PipelineConfigSpec != nil {
		in, out := &in.PipelineConfigSpec, &out.PipelineConfigSpec
		*out = new(PipelineConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(PipelineSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]PipelineEnvironment, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JenkinsfilePreviewOptions.
func (in *JenkinsfilePreviewOptions) DeepCopy() *JenkinsfilePreviewOptions {
	if in == nil {
		return nil
	}
	out := new(JenkinsfilePreviewOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JenkinsfilePreviewOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JsonV) DeepCopyInto(out *JsonV) {
	*out = *in
	if in.StringMapVal != nil {
		in, out := &in.StringMapVal, &out.StringMapVal
		*out = make(map[string]JsonV, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ArrayVal != nil {
		in, out := &in.ArrayVal, &out.ArrayVal
		*out = make([]JsonV, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JsonV.
func (in *JsonV) DeepCopy() *JsonV {
	if in == nil {
		return nil
	}
	out := new(JsonV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValue) DeepCopyInto(out *KeyValue) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValue.
func (in *KeyValue) DeepCopy() *KeyValue {
	if in == nil {
		return nil
	}
	out := new(KeyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in KeyValueSet) DeepCopyInto(out *KeyValueSet) {
	{
		in := &in
		*out = make(KeyValueSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValueSet.
func (in KeyValueSet) DeepCopy() KeyValueSet {
	if in == nil {
		return nil
	}
	out := new(KeyValueSet)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiBranchBehaviours) DeepCopyInto(out *MultiBranchBehaviours) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiBranchBehaviours.
func (in *MultiBranchBehaviours) DeepCopy() *MultiBranchBehaviours {
	if in == nil {
		return nil
	}
	out := new(MultiBranchBehaviours)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiBranchOrphan) DeepCopyInto(out *MultiBranchOrphan) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiBranchOrphan.
func (in *MultiBranchOrphan) DeepCopy() *MultiBranchOrphan {
	if in == nil {
		return nil
	}
	out := new(MultiBranchOrphan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiBranchPipeline) DeepCopyInto(out *MultiBranchPipeline) {
	*out = *in
	out.Orphaned = in.Orphaned
	out.Behaviours = in.Behaviours
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiBranchPipeline.
func (in *MultiBranchPipeline) DeepCopy() *MultiBranchPipeline {
	if in == nil {
		return nil
	}
	out := new(MultiBranchPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pipeline) DeepCopyInto(out *Pipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pipeline.
func (in *Pipeline) DeepCopy() *Pipeline {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineBlueOceanInput) DeepCopyInto(out *PipelineBlueOceanInput) {
	*out = *in
	out.PipelineBlueOceanRef = in.PipelineBlueOceanRef
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineBlueOceanParameter, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineBlueOceanInput.
func (in *PipelineBlueOceanInput) DeepCopy() *PipelineBlueOceanInput {
	if in == nil {
		return nil
	}
	out := new(PipelineBlueOceanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineBlueOceanParameter) DeepCopyInto(out *PipelineBlueOceanParameter) {
	*out = *in
	out.PipelineBlueOceanRef = in.PipelineBlueOceanRef
	out.DefaultParameterValue = in.DefaultParameterValue
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineBlueOceanParameter.
func (in *PipelineBlueOceanParameter) DeepCopy() *PipelineBlueOceanParameter {
	if in == nil {
		return nil
	}
	out := new(PipelineBlueOceanParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineBlueOceanRef) DeepCopyInto(out *PipelineBlueOceanRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineBlueOceanRef.
func (in *PipelineBlueOceanRef) DeepCopy() *PipelineBlueOceanRef {
	if in == nil {
		return nil
	}
	out := new(PipelineBlueOceanRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineBlueOceanTask) DeepCopyInto(out *PipelineBlueOceanTask) {
	*out = *in
	out.PipelineBlueOceanRef = in.PipelineBlueOceanRef
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(PipelineBlueOceanInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]PipelineBlueOceanRef, len(*in))
		copy(*out, *in)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]PipelineBlueOceanRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineBlueOceanTask.
func (in *PipelineBlueOceanTask) DeepCopy() *PipelineBlueOceanTask {
	if in == nil {
		return nil
	}
	out := new(PipelineBlueOceanTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineCause) DeepCopyInto(out *PipelineCause) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineCause.
func (in *PipelineCause) DeepCopy() *PipelineCause {
	if in == nil {
		return nil
	}
	out := new(PipelineCause)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfig) DeepCopyInto(out *PipelineConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfig.
func (in *PipelineConfig) DeepCopy() *PipelineConfig {
	if in == nil {
		return nil
	}
	out := new(PipelineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigData) DeepCopyInto(out *PipelineConfigData) {
	*out = *in
	if in.Old != nil {
		in, out := &in.Old, &out.Old
		*out = new(PipelineConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.New != nil {
		in, out := &in.New, &out.New
		*out = new(PipelineConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigData.
func (in *PipelineConfigData) DeepCopy() *PipelineConfigData {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigList) DeepCopyInto(out *PipelineConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigList.
func (in *PipelineConfigList) DeepCopy() *PipelineConfigList {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigLog) DeepCopyInto(out *PipelineConfigLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.NextStart != nil {
		in, out := &in.NextStart, &out.NextStart
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigLog.
func (in *PipelineConfigLog) DeepCopy() *PipelineConfigLog {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfigLog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigLogOptions) DeepCopyInto(out *PipelineConfigLogOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigLogOptions.
func (in *PipelineConfigLogOptions) DeepCopy() *PipelineConfigLogOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigLogOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfigLogOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigPayload) DeepCopyInto(out *PipelineConfigPayload) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigPayload.
func (in *PipelineConfigPayload) DeepCopy() *PipelineConfigPayload {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigScanOptions) DeepCopyInto(out *PipelineConfigScanOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigScanOptions.
func (in *PipelineConfigScanOptions) DeepCopy() *PipelineConfigScanOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigScanOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfigScanOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigScanResult) DeepCopyInto(out *PipelineConfigScanResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigScanResult.
func (in *PipelineConfigScanResult) DeepCopy() *PipelineConfigScanResult {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigScanResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineConfigScanResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigSpec) DeepCopyInto(out *PipelineConfigSpec) {
	*out = *in
	out.JenkinsBinding = in.JenkinsBinding
	out.RunLimits = in.RunLimits
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineParameter, len(*in))
		copy(*out, *in)
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]PipelineTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Strategy.DeepCopyInto(&out.Strategy)
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]PipelineHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Source.DeepCopyInto(&out.Source)
	in.Template.DeepCopyInto(&out.Template)
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]PipelineEnvironment, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigSpec.
func (in *PipelineConfigSpec) DeepCopy() *PipelineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigStatus) DeepCopyInto(out *PipelineConfigStatus) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigStatus.
func (in *PipelineConfigStatus) DeepCopy() *PipelineConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigTemplate) DeepCopyInto(out *PipelineConfigTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigTemplate.
func (in *PipelineConfigTemplate) DeepCopy() *PipelineConfigTemplate {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigTemplateSpec) DeepCopyInto(out *PipelineConfigTemplateSpec) {
	*out = *in
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(JenkinsAgent)
		**out = **in
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]PipelineStageInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineParameter, len(*in))
		copy(*out, *in)
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]PipelineTemplateArgumentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = new(PipelineDependency)
		(*in).DeepCopyInto(*out)
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]PipelineEnvironment, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigTemplateSpec.
func (in *PipelineConfigTemplateSpec) DeepCopy() *PipelineConfigTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineData) DeepCopyInto(out *PipelineData) {
	*out = *in
	if in.Old != nil {
		in, out := &in.Old, &out.Old
		*out = new(Pipeline)
		(*in).DeepCopyInto(*out)
	}
	if in.New != nil {
		in, out := &in.New, &out.New
		*out = new(Pipeline)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineData.
func (in *PipelineData) DeepCopy() *PipelineData {
	if in == nil {
		return nil
	}
	out := new(PipelineData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDependency) DeepCopyInto(out *PipelineDependency) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]JenkinsPlugin, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDependency.
func (in *PipelineDependency) DeepCopy() *PipelineDependency {
	if in == nil {
		return nil
	}
	out := new(PipelineDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineEnvironment) DeepCopyInto(out *PipelineEnvironment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineEnvironment.
func (in *PipelineEnvironment) DeepCopy() *PipelineEnvironment {
	if in == nil {
		return nil
	}
	out := new(PipelineEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineExportedVariables) DeepCopyInto(out *PipelineExportedVariables) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]GlobalParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineExportedVariables.
func (in *PipelineExportedVariables) DeepCopy() *PipelineExportedVariables {
	if in == nil {
		return nil
	}
	out := new(PipelineExportedVariables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineExportedVariables) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineHook) DeepCopyInto(out *PipelineHook) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]PipelineEvent, len(*in))
		copy(*out, *in)
	}
	if in.HTTPRequest != nil {
		in, out := &in.HTTPRequest, &out.HTTPRequest
		*out = new(PipelineHookHTTPRequest)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineHook.
func (in *PipelineHook) DeepCopy() *PipelineHook {
	if in == nil {
		return nil
	}
	out := new(PipelineHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineHookHTTPRequest) DeepCopyInto(out *PipelineHookHTTPRequest) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineHookHTTPRequest.
func (in *PipelineHookHTTPRequest) DeepCopy() *PipelineHookHTTPRequest {
	if in == nil {
		return nil
	}
	out := new(PipelineHookHTTPRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineInputOptions) DeepCopyInto(out *PipelineInputOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineParameter, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineInputOptions.
func (in *PipelineInputOptions) DeepCopy() *PipelineInputOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineInputOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineInputOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineInputRequest) DeepCopyInto(out *PipelineInputRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineInputRequest.
func (in *PipelineInputRequest) DeepCopy() *PipelineInputRequest {
	if in == nil {
		return nil
	}
	out := new(PipelineInputRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PipelineInputRequestList) DeepCopyInto(out *PipelineInputRequestList) {
	{
		in := &in
		*out = make(PipelineInputRequestList, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineInputRequestList.
func (in PipelineInputRequestList) DeepCopy() PipelineInputRequestList {
	if in == nil {
		return nil
	}
	out := new(PipelineInputRequestList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineInputResponse) DeepCopyInto(out *PipelineInputResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineInputResponse.
func (in *PipelineInputResponse) DeepCopy() *PipelineInputResponse {
	if in == nil {
		return nil
	}
	out := new(PipelineInputResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineInputResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineList) DeepCopyInto(out *PipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineList.
func (in *PipelineList) DeepCopy() *PipelineList {
	if in == nil {
		return nil
	}
	out := new(PipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineLog) DeepCopyInto(out *PipelineLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.NextStart != nil {
		in, out := &in.NextStart, &out.NextStart
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineLog.
func (in *PipelineLog) DeepCopy() *PipelineLog {
	if in == nil {
		return nil
	}
	out := new(PipelineLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineLog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineLogOptions) DeepCopyInto(out *PipelineLogOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineLogOptions.
func (in *PipelineLogOptions) DeepCopy() *PipelineLogOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineLogOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineLogOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineOptions) DeepCopyInto(out *PipelineOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineOptions.
func (in *PipelineOptions) DeepCopy() *PipelineOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineParameter) DeepCopyInto(out *PipelineParameter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineParameter.
func (in *PipelineParameter) DeepCopy() *PipelineParameter {
	if in == nil {
		return nil
	}
	out := new(PipelineParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinePayload) DeepCopyInto(out *PipelinePayload) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinePayload.
func (in *PipelinePayload) DeepCopy() *PipelinePayload {
	if in == nil {
		return nil
	}
	out := new(PipelinePayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineRunLimits) DeepCopyInto(out *PipelineRunLimits) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineRunLimits.
func (in *PipelineRunLimits) DeepCopy() *PipelineRunLimits {
	if in == nil {
		return nil
	}
	out := new(PipelineRunLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSource) DeepCopyInto(out *PipelineSource) {
	*out = *in
	if in.CodeRepository != nil {
		in, out := &in.CodeRepository, &out.CodeRepository
		*out = new(CodeRepositoryRef)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(PipelineSourceGit)
		**out = **in
	}
	if in.Svn != nil {
		in, out := &in.Svn, &out.Svn
		*out = new(PipelineSourceSvn)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretKeySetRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSource.
func (in *PipelineSource) DeepCopy() *PipelineSource {
	if in == nil {
		return nil
	}
	out := new(PipelineSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSourceGit) DeepCopyInto(out *PipelineSourceGit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSourceGit.
func (in *PipelineSourceGit) DeepCopy() *PipelineSourceGit {
	if in == nil {
		return nil
	}
	out := new(PipelineSourceGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSourceSvn) DeepCopyInto(out *PipelineSourceSvn) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSourceSvn.
func (in *PipelineSourceSvn) DeepCopy() *PipelineSourceSvn {
	if in == nil {
		return nil
	}
	out := new(PipelineSourceSvn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSpec) DeepCopyInto(out *PipelineSpec) {
	*out = *in
	out.JenkinsBinding = in.JenkinsBinding
	out.PipelineConfig = in.PipelineConfig
	out.Cause = in.Cause
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineParameter, len(*in))
		copy(*out, *in)
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]PipelineTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Strategy.DeepCopyInto(&out.Strategy)
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]PipelineHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Source.DeepCopyInto(&out.Source)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSpec.
func (in *PipelineSpec) DeepCopy() *PipelineSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStage) DeepCopyInto(out *PipelineStage) {
	*out = *in
	out.Display = in.Display
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]PipelineTemplateTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStage.
func (in *PipelineStage) DeepCopy() *PipelineStage {
	if in == nil {
		return nil
	}
	out := new(PipelineStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStageInstance) DeepCopyInto(out *PipelineStageInstance) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]PipelineTemplateTaskInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStageInstance.
func (in *PipelineStageInstance) DeepCopy() *PipelineStageInstance {
	if in == nil {
		return nil
	}
	out := new(PipelineStageInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStatus) DeepCopyInto(out *PipelineStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Jenkins != nil {
		in, out := &in.Jenkins, &out.Jenkins
		*out = new(PipelineStatusJenkins)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStatus.
func (in *PipelineStatus) DeepCopy() *PipelineStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStatusJenkins) DeepCopyInto(out *PipelineStatusJenkins) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStatusJenkins.
func (in *PipelineStatusJenkins) DeepCopy() *PipelineStatusJenkins {
	if in == nil {
		return nil
	}
	out := new(PipelineStatusJenkins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStrategy) DeepCopyInto(out *PipelineStrategy) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(PipelineConfigTemplate)
		(*in).DeepCopyInto(*out)
	}
	out.Jenkins = in.Jenkins
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStrategy.
func (in *PipelineStrategy) DeepCopy() *PipelineStrategy {
	if in == nil {
		return nil
	}
	out := new(PipelineStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStrategyJenkins) DeepCopyInto(out *PipelineStrategyJenkins) {
	*out = *in
	out.MultiBranch = in.MultiBranch
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStrategyJenkins.
func (in *PipelineStrategyJenkins) DeepCopy() *PipelineStrategyJenkins {
	if in == nil {
		return nil
	}
	out := new(PipelineStrategyJenkins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTask) DeepCopyInto(out *PipelineTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]PipelineBlueOceanTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTask.
func (in *PipelineTask) DeepCopy() *PipelineTask {
	if in == nil {
		return nil
	}
	out := new(PipelineTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskApprove) DeepCopyInto(out *PipelineTaskApprove) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskApprove.
func (in *PipelineTaskApprove) DeepCopy() *PipelineTaskApprove {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskApprove)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskArgument) DeepCopyInto(out *PipelineTaskArgument) {
	*out = *in
	out.Schema = in.Schema
	in.Display.DeepCopyInto(&out.Display)
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(PipelineTaskArgumentValidation)
		**out = **in
	}
	if in.Relation != nil {
		in, out := &in.Relation, &out.Relation
		*out = make([]PipelineTaskArgumentAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskArgument.
func (in *PipelineTaskArgument) DeepCopy() *PipelineTaskArgument {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskArgument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskArgumentAction) DeepCopyInto(out *PipelineTaskArgumentAction) {
	*out = *in
	in.When.DeepCopyInto(&out.When)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskArgumentAction.
func (in *PipelineTaskArgumentAction) DeepCopy() *PipelineTaskArgumentAction {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskArgumentAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskArgumentDisplay) DeepCopyInto(out *PipelineTaskArgumentDisplay) {
	*out = *in
	out.Name = in.Name
	out.Description = in.Description
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskArgumentDisplay.
func (in *PipelineTaskArgumentDisplay) DeepCopy() *PipelineTaskArgumentDisplay {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskArgumentDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskArgumentSchema) DeepCopyInto(out *PipelineTaskArgumentSchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskArgumentSchema.
func (in *PipelineTaskArgumentSchema) DeepCopy() *PipelineTaskArgumentSchema {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskArgumentSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskArgumentValidation) DeepCopyInto(out *PipelineTaskArgumentValidation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskArgumentValidation.
func (in *PipelineTaskArgumentValidation) DeepCopy() *PipelineTaskArgumentValidation {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskArgumentValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskArgumentWhen) DeepCopyInto(out *PipelineTaskArgumentWhen) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make([]RelationWhenItem, len(*in))
		copy(*out, *in)
	}
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make([]RelationWhenItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskArgumentWhen.
func (in *PipelineTaskArgumentWhen) DeepCopy() *PipelineTaskArgumentWhen {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskArgumentWhen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskOption) DeepCopyInto(out *PipelineTaskOption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskOption.
func (in *PipelineTaskOption) DeepCopy() *PipelineTaskOption {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskOptions) DeepCopyInto(out *PipelineTaskOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskOptions.
func (in *PipelineTaskOptions) DeepCopy() *PipelineTaskOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTaskOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskTemplate) DeepCopyInto(out *PipelineTaskTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskTemplate.
func (in *PipelineTaskTemplate) DeepCopy() *PipelineTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTaskTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskTemplateList) DeepCopyInto(out *PipelineTaskTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskTemplateList.
func (in *PipelineTaskTemplateList) DeepCopy() *PipelineTaskTemplateList {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTaskTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTaskTemplateSpec) DeepCopyInto(out *PipelineTaskTemplateSpec) {
	*out = *in
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(JenkinsAgent)
		**out = **in
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]GlobalParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineParameter, len(*in))
		copy(*out, *in)
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]PipelineTaskArgument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = new(PipelineDependency)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTaskTemplateSpec.
func (in *PipelineTaskTemplateSpec) DeepCopy() *PipelineTaskTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineTaskTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplate) DeepCopyInto(out *PipelineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplate.
func (in *PipelineTemplate) DeepCopy() *PipelineTemplate {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateArgument) DeepCopyInto(out *PipelineTemplateArgument) {
	*out = *in
	out.Schema = in.Schema
	if in.Binding != nil {
		in, out := &in.Binding, &out.Binding
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Display.DeepCopyInto(&out.Display)
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(PipelineTaskArgumentValidation)
		**out = **in
	}
	if in.Relation != nil {
		in, out := &in.Relation, &out.Relation
		*out = make([]PipelineTaskArgumentAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateArgument.
func (in *PipelineTemplateArgument) DeepCopy() *PipelineTemplateArgument {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateArgument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateArgumentGroup) DeepCopyInto(out *PipelineTemplateArgumentGroup) {
	*out = *in
	out.DisplayName = in.DisplayName
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineTemplateArgumentValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateArgumentGroup.
func (in *PipelineTemplateArgumentGroup) DeepCopy() *PipelineTemplateArgumentGroup {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateArgumentGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateArgumentValue) DeepCopyInto(out *PipelineTemplateArgumentValue) {
	*out = *in
	in.PipelineTemplateArgument.DeepCopyInto(&out.PipelineTemplateArgument)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateArgumentValue.
func (in *PipelineTemplateArgumentValue) DeepCopy() *PipelineTemplateArgumentValue {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateArgumentValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateList) DeepCopyInto(out *PipelineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateList.
func (in *PipelineTemplateList) DeepCopy() *PipelineTemplateList {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateMold) DeepCopyInto(out *PipelineTemplateMold) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateMold.
func (in *PipelineTemplateMold) DeepCopy() *PipelineTemplateMold {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateMold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateRef) DeepCopyInto(out *PipelineTemplateRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateRef.
func (in *PipelineTemplateRef) DeepCopy() *PipelineTemplateRef {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateSource) DeepCopyInto(out *PipelineTemplateSource) {
	*out = *in
	out.PipelineTemplateRef = in.PipelineTemplateRef
	if in.PipelineTemplate != nil {
		in, out := &in.PipelineTemplate, &out.PipelineTemplate
		*out = new(PipelineTemplateMold)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateSource.
func (in *PipelineTemplateSource) DeepCopy() *PipelineTemplateSource {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateSpec) DeepCopyInto(out *PipelineTemplateSpec) {
	*out = *in
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(JenkinsAgent)
		**out = **in
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]PipelineStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PipelineParameter, len(*in))
		copy(*out, *in)
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]PipelineTemplateArgumentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]PipelineEnvironment, len(*in))
		copy(*out, *in)
	}
	out.Options = in.Options
	out.Triggers = in.Triggers
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make(map[string][]PipelineTemplateTask, len(*in))
		for key, val := range *in {
			var outVal []PipelineTemplateTask
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]PipelineTemplateTask, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	in.ConstValues.DeepCopyInto(&out.ConstValues)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateSpec.
func (in *PipelineTemplateSpec) DeepCopy() *PipelineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateTask) DeepCopyInto(out *PipelineTemplateTask) {
	*out = *in
	out.Display = in.Display
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(JenkinsAgent)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(PipelineTaskOption)
		**out = **in
	}
	if in.Approve != nil {
		in, out := &in.Approve, &out.Approve
		*out = new(PipelineTaskApprove)
		**out = **in
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]PipelineEnvironment, len(*in))
		copy(*out, *in)
	}
	if in.Relation != nil {
		in, out := &in.Relation, &out.Relation
		*out = make([]PipelineTaskArgumentAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateTask.
func (in *PipelineTemplateTask) DeepCopy() *PipelineTemplateTask {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateTaskInstance) DeepCopyInto(out *PipelineTemplateTaskInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateTaskInstance.
func (in *PipelineTemplateTaskInstance) DeepCopy() *PipelineTemplateTaskInstance {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateTaskInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateTaskInstanceSpec) DeepCopyInto(out *PipelineTemplateTaskInstanceSpec) {
	*out = *in
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(JenkinsAgent)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(PipelineTaskOption)
		**out = **in
	}
	if in.Approve != nil {
		in, out := &in.Approve, &out.Approve
		*out = new(PipelineTaskApprove)
		**out = **in
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]PipelineEnvironment, len(*in))
		copy(*out, *in)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]GlobalParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]PipelineTemplateArgument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Relation != nil {
		in, out := &in.Relation, &out.Relation
		*out = make([]PipelineTaskArgumentAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateTaskInstanceSpec.
func (in *PipelineTemplateTaskInstanceSpec) DeepCopy() *PipelineTemplateTaskInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateTaskInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplateWithValue) DeepCopyInto(out *PipelineTemplateWithValue) {
	*out = *in
	in.PipelineTemplateSource.DeepCopyInto(&out.PipelineTemplateSource)
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GraphValues != nil {
		in, out := &in.GraphValues, &out.GraphValues
		*out = make(map[string]KeyValueSet, len(*in))
		for key, val := range *in {
			var outVal []KeyValue
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(KeyValueSet, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplateWithValue.
func (in *PipelineTemplateWithValue) DeepCopy() *PipelineTemplateWithValue {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateWithValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTestReport) DeepCopyInto(out *PipelineTestReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(PipelineTestReportSummary)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineTestReportItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTestReport.
func (in *PipelineTestReport) DeepCopy() *PipelineTestReport {
	if in == nil {
		return nil
	}
	out := new(PipelineTestReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTestReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTestReportItem) DeepCopyInto(out *PipelineTestReportItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTestReportItem.
func (in *PipelineTestReportItem) DeepCopy() *PipelineTestReportItem {
	if in == nil {
		return nil
	}
	out := new(PipelineTestReportItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTestReportOptions) DeepCopyInto(out *PipelineTestReportOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTestReportOptions.
func (in *PipelineTestReportOptions) DeepCopy() *PipelineTestReportOptions {
	if in == nil {
		return nil
	}
	out := new(PipelineTestReportOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineTestReportOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTestReportSummary) DeepCopyInto(out *PipelineTestReportSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTestReportSummary.
func (in *PipelineTestReportSummary) DeepCopy() *PipelineTestReportSummary {
	if in == nil {
		return nil
	}
	out := new(PipelineTestReportSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTriggeSchedule) DeepCopyInto(out *PipelineTriggeSchedule) {
	*out = *in
	if in.Weeks != nil {
		in, out := &in.Weeks, &out.Weeks
		*out = make([]Week, len(*in))
		copy(*out, *in)
	}
	if in.Times != nil {
		in, out := &in.Times, &out.Times
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTriggeSchedule.
func (in *PipelineTriggeSchedule) DeepCopy() *PipelineTriggeSchedule {
	if in == nil {
		return nil
	}
	out := new(PipelineTriggeSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTrigger) DeepCopyInto(out *PipelineTrigger) {
	*out = *in
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(PipelineTriggerCron)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeChange != nil {
		in, out := &in.CodeChange, &out.CodeChange
		*out = new(PipelineTriggerCodeChange)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTrigger.
func (in *PipelineTrigger) DeepCopy() *PipelineTrigger {
	if in == nil {
		return nil
	}
	out := new(PipelineTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTriggerCodeChange) DeepCopyInto(out *PipelineTriggerCodeChange) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTriggerCodeChange.
func (in *PipelineTriggerCodeChange) DeepCopy() *PipelineTriggerCodeChange {
	if in == nil {
		return nil
	}
	out := new(PipelineTriggerCodeChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTriggerCron) DeepCopyInto(out *PipelineTriggerCron) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(PipelineTriggeSchedule)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTriggerCron.
func (in *PipelineTriggerCron) DeepCopy() *PipelineTriggerCron {
	if in == nil {
		return nil
	}
	out := new(PipelineTriggerCron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTriggers) DeepCopyInto(out *PipelineTriggers) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTriggers.
func (in *PipelineTriggers) DeepCopy() *PipelineTriggers {
	if in == nil {
		return nil
	}
	out := new(PipelineTriggers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationWhenItem) DeepCopyInto(out *RelationWhenItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationWhenItem.
func (in *RelationWhenItem) DeepCopy() *RelationWhenItem {
	if in == nil {
		return nil
	}
	out := new(RelationWhenItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySetRef) DeepCopyInto(out *SecretKeySetRef) {
	*out = *in
	out.SecretReference = in.SecretReference
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySetRef.
func (in *SecretKeySetRef) DeepCopy() *SecretKeySetRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeySetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.HTTPStatus != nil {
		in, out := &in.HTTPStatus, &out.HTTPStatus
		*out = new(HostPortStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]BindingCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskConstValue) DeepCopyInto(out *TaskConstValue) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Options = in.Options
	out.Approve = in.Approve
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskConstValue.
func (in *TaskConstValue) DeepCopy() *TaskConstValue {
	if in == nil {
		return nil
	}
	out := new(TaskConstValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateStatus) DeepCopyInto(out *TemplateStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateStatus.
func (in *TemplateStatus) DeepCopy() *TemplateStatus {
	if in == nil {
		return nil
	}
	out := new(TemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in BindingConditions) DeepCopyInto(out *BindingConditions) {
	{
		in := &in
		*out = make(BindingConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingConditions.
func (in BindingConditions) DeepCopy() BindingConditions {
	if in == nil {
		return nil
	}
	out := new(BindingConditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityAnalyzeMetric) DeepCopyInto(out *CodeQualityAnalyzeMetric) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityAnalyzeMetric.
func (in *CodeQualityAnalyzeMetric) DeepCopy() *CodeQualityAnalyzeMetric {
	if in == nil {
		return nil
	}
	out := new(CodeQualityAnalyzeMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityCondition) DeepCopyInto(out *CodeQualityCondition) {
	*out = *in
	in.BindingCondition.DeepCopyInto(&out.BindingCondition)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make(map[string]CodeQualityAnalyzeMetric, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityCondition.
func (in *CodeQualityCondition) DeepCopy() *CodeQualityCondition {
	if in == nil {
		return nil
	}
	out := new(CodeQualityCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityProject) DeepCopyInto(out *CodeQualityProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityProject.
func (in *CodeQualityProject) DeepCopy() *CodeQualityProject {
	if in == nil {
		return nil
	}
	out := new(CodeQualityProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeQualityProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityProjectInfo) DeepCopyInto(out *CodeQualityProjectInfo) {
	*out = *in
	if in.LastAnalysis != nil {
		in, out := &in.LastAnalysis, &out.LastAnalysis
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityProjectInfo.
func (in *CodeQualityProjectInfo) DeepCopy() *CodeQualityProjectInfo {
	if in == nil {
		return nil
	}
	out := new(CodeQualityProjectInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityProjectList) DeepCopyInto(out *CodeQualityProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeQualityProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityProjectList.
func (in *CodeQualityProjectList) DeepCopy() *CodeQualityProjectList {
	if in == nil {
		return nil
	}
	out := new(CodeQualityProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeQualityProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityProjectSpec) DeepCopyInto(out *CodeQualityProjectSpec) {
	*out = *in
	out.CodeQualityTool = in.CodeQualityTool
	out.CodeQualityBinding = in.CodeQualityBinding
	out.CodeRepository = in.CodeRepository
	in.Project.DeepCopyInto(&out.Project)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityProjectSpec.
func (in *CodeQualityProjectSpec) DeepCopy() *CodeQualityProjectSpec {
	if in == nil {
		return nil
	}
	out := new(CodeQualityProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeQualityProjectStatus) DeepCopyInto(out *CodeQualityProjectStatus) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.HTTPStatus != nil {
		in, out := &in.HTTPStatus, &out.HTTPStatus
		*out = new(HostPortStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeQualityConditions != nil {
		in, out := &in.CodeQualityConditions, &out.CodeQualityConditions
		*out = make([]CodeQualityCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeQualityProjectStatus.
func (in *CodeQualityProjectStatus) DeepCopy() *CodeQualityProjectStatus {
	if in == nil {
		return nil
	}
	out := new(CodeQualityProjectStatus)
	in.DeepCopyInto(out)
	return out
}
